# Generated by Django 4.2.3 on 2023-07-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.IntegerField(default=50, verbose_name='Start Location X')),
                ('start_y', models.IntegerField(default=50, verbose_name='Start Location Y')),
                ('end_x', models.IntegerField(default=50, verbose_name='End Location X')),
                ('end_y', models.IntegerField(default=50, verbose_name='End Location Y')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_walls', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Wall',
                'verbose_name_plural': 'Parameter Set Walls',
            },
        ),
    ]
