# Generated by Django 4.2.3 on 2023-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_parametersetwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetwall',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
