# Generated by Django 4.2.3 on 2023-07-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_end_y_parametersetwall_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetwall',
            options={'ordering': ['id'], 'verbose_name': 'Parameter Set Wall', 'verbose_name_plural': 'Parameter Set Walls'},
        ),
        migrations.AlterField(
            model_name='parametersetwall',
            name='height',
            field=models.IntegerField(default=50, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='parametersetwall',
            name='start_x',
            field=models.IntegerField(default=50, verbose_name='Location X'),
        ),
        migrations.AlterField(
            model_name='parametersetwall',
            name='start_y',
            field=models.IntegerField(default=50, verbose_name='Location Y'),
        ),
        migrations.AlterField(
            model_name='parametersetwall',
            name='width',
            field=models.IntegerField(default=50, verbose_name='Width'),
        ),
        migrations.CreateModel(
            name='ParameterSetGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('x', models.IntegerField(default=50, verbose_name='Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('tint', models.CharField(default='0x000000', max_length=8, verbose_name='Tint (Hex Color)')),
                ('texture', models.CharField(default='Name Here', verbose_name='Texture Name')),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('scale', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_grounds', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Ground Element',
                'verbose_name_plural': 'Parameter Set Ground Elements',
                'ordering': ['id'],
            },
        ),
    ]
