# Generated by Django 4.2.3 on 2023-07-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_parametersetwall_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, default='Even or Odd', null=True, verbose_name='Info')),
                ('good_one', models.CharField(choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Cherry', max_length=100, verbose_name='Good One')),
                ('good_two', models.CharField(choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Blueberry', max_length=100, verbose_name='Good Two')),
                ('start_on_period', models.IntegerField(default=1, verbose_name='Start on Period')),
                ('reset_every_n_periods', models.IntegerField(default=2, verbose_name='Reset Every N Periods')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_field_types', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Field Type',
                'verbose_name_plural': 'Parameter Set Field Types',
                'ordering': ['id'],
            },
        ),
    ]
