# Generated by Django 4.2.3 on 2023-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_parametersetfieldtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetfieldtype',
            name='display_text',
            field=models.TextField(blank=True, default='Display Text', null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='info',
            field=models.TextField(blank=True, default='Description of Field Type', null=True, verbose_name='Info'),
        ),
    ]
