# Generated by Django 4.2.3 on 2023-07-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_parametersetfieldtype_display_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='info',
            field=models.TextField(default='Description of Field Type', verbose_name='Info'),
        ),
        migrations.CreateModel(
            name='ParameterSetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=50, verbose_name='Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_fields_a', to='main.parameterset')),
                ('parameter_set_field_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter_set_fields_b', to='main.parametersetfieldtype')),
                ('parameter_set_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter_set_fields_c', to='main.parametersetplayer')),
            ],
            options={
                'verbose_name': 'Parameter Set Field',
                'verbose_name_plural': 'Parameter Set Fields',
                'ordering': ['id'],
            },
        ),
    ]
