# Generated by Django 4.2.3 on 2023-07-21 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_parametersetfieldtype_info_parametersetfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetfield',
            name='parameter_set_field_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_fields_b', to='main.parametersetfieldtype'),
        ),
        migrations.AlterField(
            model_name='parametersetfield',
            name='parameter_set_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_fields_c', to='main.parametersetplayer'),
        ),
    ]
