# Generated by Django 4.2.3 on 2023-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_parametersetplayer_house_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='field_height',
            field=models.IntegerField(default=500, verbose_name='Height of field in pixels'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='field_width',
            field=models.IntegerField(default=300, verbose_name='Width of field in pixels'),
        ),
    ]
