# Generated by Django 4.2.3 on 2023-07-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_parameterset_field_height_parameterset_field_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='good_one',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Cherry', max_length=100, null=True, verbose_name='Good One'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='good_three',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Pineapple', max_length=100, null=True, verbose_name='Good Three'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='good_two',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Blueberry', max_length=100, null=True, verbose_name='Good Two'),
        ),
    ]
