# Generated by Django 4.2.3 on 2023-07-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_parametersetplayer_good_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='house_height',
            field=models.IntegerField(default=500, verbose_name='Height of house in pixels'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='house_width',
            field=models.IntegerField(default=350, verbose_name='Width of house in pixels'),
        ),
    ]
