# Generated by Django 4.2.3 on 2023-07-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_parameterset_house_height_parameterset_house_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_scale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
