# Generated by Django 4.2.3 on 2023-07-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_parameterset_avatar_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='avatar_scale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Avatar Scale'),
        ),
    ]
