# Generated by Django 4.2.3 on 2023-07-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_parameterset_production_alpha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='production_alpha',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='production_omega',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='production_rho',
        ),
    ]
