# Generated by Django 4.2.3 on 2023-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_parameterset_production_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='production_alpha',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=6, verbose_name='Production Parameter alpha'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='production_omega',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=6, verbose_name='Production Parameter omega'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='production_rho',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=6, verbose_name='Production Parameter rho'),
        ),
    ]
