# Generated by Django 4.2.3 on 2023-07-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_parameterset_production_alpha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='production_time',
            new_name='production_effort',
        ),
    ]
