# Generated by Django 4.2.3 on 2023-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_parameterset_production_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='consumption_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionperiod',
            name='production_completed',
            field=models.BooleanField(default=False),
        ),
    ]
