# Generated by Django 4.2.3 on 2023-08-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_session_world_state_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_one_alpha',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good One Production Alpha'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_one_omega',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good One Production Omega'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_one_rho',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good One Production Rho'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_two_alpha',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good Two Production Alpha'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_two_omega',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good Two Production Omega'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_two_rho',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7, verbose_name='Good Two Production Rho'),
        ),
    ]
