# Generated by Django 4.2.3 on 2023-08-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_parameterset_health_loss_per_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='heath_gain_per_sleep_second',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4, verbose_name='Health Gain per Sleep Second'),
        ),
    ]
