# Generated by Django 4.2.3 on 2023-08-08 17:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_parameterset_heath_gain_per_sleep_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='timer_actions',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
