# Generated by Django 4.2.3 on 2023-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_sessionperiod_timer_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='cents_per_second',
            field=models.DecimalField(decimal_places=5, default=0.016, max_digits=7, verbose_name='Cents per Second'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='consumption_alpha',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=7, verbose_name='Consumption Alpha'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='consumption_beta',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=7, verbose_name='Consumption Beta'),
        ),
    ]
