# Generated by Django 4.2.3 on 2023-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_parameterset_cents_per_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='attack_cost',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Attack Cost to Health'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='attack_damage',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='Attack Damage to Health'),
        ),
    ]
