# Generated by Django 4.2.3 on 2023-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_parameterset_attack_cost_parameterset_attack_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='night_length',
            field=models.IntegerField(default=10, verbose_name='Night Length'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='sleep_benefit',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Sleep Benefit to Health'),
        ),
    ]
