# Generated by Django 4.2.3 on 2023-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_parameterset_night_length_parameterset_sleep_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_bound_box_percent',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=3, verbose_name='Avatar Bound Box Percent'),
        ),
    ]
