# Generated by Django 4.2.3 on 2023-08-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_parameterset_avatar_bound_box_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetfieldtype',
            old_name='good_one',
            new_name='good_one_ft',
        ),
        migrations.RenameField(
            model_name='parametersetfieldtype',
            old_name='good_two',
            new_name='good_two_ft',
        ),
    ]
