# Generated by Django 4.2.3 on 2023-08-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_rename_good_one_parametersetfieldtype_good_one_ft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_groups', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Group',
                'verbose_name_plural': 'Parameter Set Groups',
                'ordering': ['name'],
            },
        ),
    ]
