# Generated by Django 4.2.3 on 2023-08-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_parametersetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='parameter_set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_players_b', to='main.parametersetgroup'),
        ),
    ]
