# Generated by Django 4.2.3 on 2023-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_parametersetplayer_parameter_set_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetgroup',
            name='name',
            field=models.CharField(blank=True, default='Name Here', max_length=255, null=True),
        ),
    ]
