# Generated by Django 4.2.3 on 2023-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_parametersetgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='allow_stealing',
            field=models.BooleanField(default=False, verbose_name='Allow Stealing'),
        ),
    ]
