# Generated by Django 4.2.3 on 2023-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_parameterset_allow_stealing'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='break_frequency',
            field=models.IntegerField(default=7, verbose_name='Break Frequency'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='break_length',
            field=models.IntegerField(default=100, verbose_name='Break Length'),
        ),
    ]
