# Generated by Django 4.2.3 on 2023-08-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_parameterset_break_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('start_period', models.IntegerField(default=1, verbose_name='Starting Period')),
                ('start_time', models.IntegerField(default=30, verbose_name='Starting Time')),
                ('end_period', models.IntegerField(default=1, verbose_name='Width')),
                ('end_time', models.IntegerField(default=0, verbose_name='Height')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_notices', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Notice',
                'verbose_name_plural': 'Parameter Set Notices',
                'ordering': ['id'],
            },
        ),
    ]
