# Generated by Django 4.2.3 on 2023-08-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_parametersetnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetBarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('start_x', models.IntegerField(default=50, verbose_name='Location X')),
                ('start_y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('text', models.TextField(default='Closed until period N', verbose_name='Text')),
                ('rotation', models.DecimalField(decimal_places=5, default=0, max_digits=7, verbose_name='Rotation')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_barriers', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Barrier',
                'verbose_name_plural': 'Parameter Set Barriers',
                'ordering': ['id'],
            },
        ),
    ]
