# Generated by Django 4.2.3 on 2023-08-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_parametersetbarrier_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetbarrier',
            old_name='groups',
            new_name='parameter_set_groups',
        ),
    ]
