# Generated by Django 4.2.3 on 2023-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_rename_groups_parametersetbarrier_parameter_set_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetbarrier',
            name='rotation',
            field=models.IntegerField(default=0, verbose_name='Rotation'),
        ),
    ]
