# Generated by Django 4.2.3 on 2023-08-24 17:09

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_parametersetbarrier_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='chat_mode',
            field=models.CharField(choices=[('Full', 'Full'), ('Limited', 'Limited')], default='Full', max_length=100),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='chat_rules',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
