# Generated by Django 4.2.3 on 2023-08-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_parameterset_chat_mode_parameterset_chat_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameterset',
            old_name='chat_rules',
            new_name='chat_rules_letters',
        ),
    ]
