# Generated by Django 4.2.3 on 2023-08-24 18:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_rename_chat_rules_parameterset_chat_rules_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='chat_rules_word_list',
            field=models.TextField(default='', verbose_name='Chat Words Allowed List'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='chat_mode',
            field=models.CharField(choices=[('Full', 'Full'), ('Limited', 'Limited')], default='Full', max_length=100, verbose_name='Chat Mode'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='chat_rules_letters',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Chat Letter Mapping'),
        ),
    ]
