# Generated by Django 4.2.3 on 2023-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_parameterset_chat_rules_word_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='chat_rules_word_list',
            field=models.TextField(blank=True, default='', verbose_name='Chat Words Allowed List'),
        ),
    ]
