# Generated by Django 4.2.3 on 2023-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_parameterset_chat_rules_word_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='display_text',
            field=models.CharField(blank=True, default='Display Text', max_length=100, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='info',
            field=models.CharField(default='Description of Field Type', max_length=100, verbose_name='Info'),
        ),
    ]
