# Generated by Django 4.2.3 on 2023-08-28 20:30

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_parametersetfieldtype_display_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetGrove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=50, verbose_name='Start Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Start Location Y')),
                ('good', models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Cherry', max_length=100, null=True, verbose_name='Good One')),
                ('levels', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Levels')),
                ('hex_color', models.CharField(default='0x000000', max_length=8, verbose_name='Hex Color')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_groves_a', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Grove',
                'verbose_name_plural': 'Parameter Set Grove',
                'ordering': ['good'],
            },
        ),
    ]
