# Generated by Django 4.2.3 on 2023-08-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_parametersetgrove'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgrove',
            name='drought_on_period',
            field=models.IntegerField(default=14, verbose_name='Drought On Period'),
        ),
        migrations.AddField(
            model_name='parametersetgrove',
            name='max_levels',
            field=models.IntegerField(default=4, verbose_name='Max Levels'),
        ),
    ]
