# Generated by Django 4.2.3 on 2023-08-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_parametersetgrove_drought_on_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgrove',
            name='drought_level',
            field=models.IntegerField(default=1, verbose_name='Drought Level'),
        ),
    ]
