# Generated by Django 4.2.3 on 2023-08-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_parametersetgrove_drought_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetgrove',
            name='max_levels',
        ),
    ]
