# Generated by Django 4.2.3 on 2023-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_remove_parametersetgrove_max_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='growth_completed',
            field=models.BooleanField(default=False),
        ),
    ]
