# Generated by Django 4.2.3 on 2023-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_sessionperiod_growth_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='max_grove_harvests',
            field=models.IntegerField(default=1, verbose_name='Max Grove Harvests'),
        ),
    ]
