# Generated by Django 4.2.3 on 2023-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_parameterset_max_grove_harvests'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='allow_attacks',
            field=models.BooleanField(default=False, verbose_name='Allow Attacks'),
        ),
    ]
