# Generated by Django 4.2.3 on 2023-09-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_parameterset_allow_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgrove',
            name='parameter_set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_groves_b', to='main.parametersetgroup'),
        ),
    ]
