# Generated by Django 4.2.3 on 2023-09-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_parametersetgrove_parameter_set_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetgrove',
            options={'ordering': ['id'], 'verbose_name': 'Parameter Set Grove', 'verbose_name_plural': 'Parameter Set Grove'},
        ),
    ]
