# Generated by Django 4.2.3 on 2023-09-06 21:31

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_alter_parametersetgrove_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='summary_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Summary Data'),
        ),
    ]
