# Generated by Django 4.2.3 on 2023-09-08 15:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_session_summary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='summary_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Summary Data'),
        ),
    ]
