# Generated by Django 4.2.3 on 2023-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_session_summary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgrove',
            name='info',
            field=models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info'),
        ),
    ]
