# Generated by Django 4.2.3 on 2023-09-11 18:37

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_parameterset_consumption_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info')),
                ('x', models.IntegerField(default=50, verbose_name='Start Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Start Location Y')),
                ('good', models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Pineapple', 'Pineapple'), ('Blueberry', 'Blueberry')], default='Cherry', max_length=100, null=True, verbose_name='Good One')),
                ('levels', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Levels')),
                ('drought_on_period', models.IntegerField(default=14, verbose_name='Drought On Period')),
                ('drought_level', models.IntegerField(default=1, verbose_name='Drought Level')),
                ('hex_color', models.CharField(default='0x000000', max_length=8, verbose_name='Hex Color')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Set Patch',
                'verbose_name_plural': 'Parameter Set Patch',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='max_grove_harvests',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='max_patch_harvests',
            field=models.IntegerField(default=1, verbose_name='Max Patch Harvests'),
        ),
        migrations.DeleteModel(
            name='ParameterSetGrove',
        ),
        migrations.AddField(
            model_name='parametersetpatch',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_patches_a', to='main.parameterset'),
        ),
        migrations.AddField(
            model_name='parametersetpatch',
            name='parameter_set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_patches_b', to='main.parametersetgroup'),
        ),
    ]
