# Generated by Django 4.2.3 on 2023-09-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_parametersetpatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='starting_health',
            field=models.IntegerField(default=75, verbose_name='Starting Health'),
        ),
    ]
