# Generated by Django 4.2.5 on 2023-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_parameterset_starting_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='good_mode',
            field=models.CharField(choices=[('Two', 'Two'), ('Three', 'Three')], default='Three', max_length=100, verbose_name='Good Mode'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_one_ft',
            field=models.CharField(choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Cherry', max_length=100, verbose_name='Good One'),
        ),
        migrations.AlterField(
            model_name='parametersetfieldtype',
            name='good_two_ft',
            field=models.CharField(choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Blueberry', max_length=100, verbose_name='Good Two'),
        ),
        migrations.AlterField(
            model_name='parametersetpatch',
            name='good',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Cherry', max_length=100, null=True, verbose_name='Good One'),
        ),
        migrations.AlterField(
            model_name='parametersetplayer',
            name='good_one',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Cherry', max_length=100, null=True, verbose_name='Good One'),
        ),
        migrations.AlterField(
            model_name='parametersetplayer',
            name='good_three',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Pineapple', max_length=100, null=True, verbose_name='Good Three'),
        ),
        migrations.AlterField(
            model_name='parametersetplayer',
            name='good_two',
            field=models.CharField(blank=True, choices=[('Cherry', 'Cherry'), ('Blueberry', 'Blueberry'), ('Pineapple', 'Pineapple')], default='Blueberry', max_length=100, null=True, verbose_name='Good Two'),
        ),
    ]
