# Generated by Django 4.2.3 on 2023-09-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_parameterset_good_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetpatch',
            old_name='drought_level',
            new_name='shock_level',
        ),
        migrations.RenameField(
            model_name='parametersetpatch',
            old_name='drought_on_period',
            new_name='shock_on_period',
        ),
    ]
