# Generated by Django 4.2.3 on 2023-09-12 20:21

import django.core.serializers.json
from django.db import migrations, models

from main.models import ParameterSetPatch

def do_python(apps, schema_editor):
    '''
    setup default shock levels
    '''

    ParameterSetPatch.objects.all().update(shock_levels={"1":{"value":0, "harvested":False}})

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_remove_parametersetpatch_shock_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetpatch',
            name='shock_levels',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Shock Levels'),
        ),
       migrations.RunPython(do_python),
    ]
