# Generated by Django 4.2.3 on 2023-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_parametersetpatch_shock_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='id_label',
            field=models.CharField(default='Color', max_length=20, verbose_name='ID Label'),
        ),
    ]
