# Generated by Django 4.2.5 on 2023-09-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_alter_parametersetplayer_id_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='action_page_attacks',
            field=models.IntegerField(default=6, verbose_name='Required Action: Production'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_harvest',
            field=models.IntegerField(default=3, verbose_name='Required Action: Production'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_house',
            field=models.IntegerField(default=4, verbose_name='Required Action: Production'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_move',
            field=models.IntegerField(default=1, verbose_name='Required Action: Production'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_sleep',
            field=models.IntegerField(default=5, verbose_name='Required Action: Production'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameter_sets', to='main.instructionset'),
        ),
    ]
