# Generated by Django 4.2.5 on 2023-09-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_instructionset_action_page_attacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_sets', to='main.instructionset'),
        ),
    ]
