# Generated by Django 4.2.3 on 2023-09-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_helpdocssubject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdocssubject',
            name='instruction_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_docs_subject', to='main.instructionset'),
        ),
    ]
