# Generated by Django 4.2.5 on 2023-09-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_parametersethat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='parameter_set_hat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_players_c', to='main.parametersethat'),
        ),
    ]
