# Generated by Django 4.2.5 on 2023-09-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_parametersetplayer_parameter_set_hat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='enable_hats',
            field=models.BooleanField(default=False, verbose_name='Enable Hats'),
        ),
    ]
