# Generated by Django 4.2.5 on 2023-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_alter_instructionset_action_page_attacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_animation_speed',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Animation Speed'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='avatar_move_speed',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Move Speed'),
        ),
    ]
