# Generated by Django 4.2.5 on 2023-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_instructionset_action_page_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='enable_emoji',
            field=models.BooleanField(default=True, verbose_name='Enable Emoji'),
        ),
    ]
