# Generated by Django 4.2.5 on 2023-11-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_parameterset_enable_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetground',
            name='tint',
            field=models.CharField(default='0xFFFFFF', max_length=8, verbose_name='Tint (Hex Color)'),
        ),
    ]
