# Generated by Django 4.2.5 on 2023-11-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_alter_parametersetground_tint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetpatch',
            options={'ordering': ['info'], 'verbose_name': 'Parameter Set Patch', 'verbose_name_plural': 'Parameter Set Patch'},
        ),
        migrations.AddField(
            model_name='parameterset',
            name='patch_harvest_mode',
            field=models.CharField(choices=[('Any', 'Any'), ('Once per Group', 'Once per Group')], default='Any', max_length=100, verbose_name='Patch Harvest Mode'),
        ),
    ]
