# Generated by Django 4.2.5 on 2023-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_parametersetpatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetbarrier',
            name='parameter_set_players',
            field=models.ManyToManyField(related_name='parameter_set_barriers_c', to='main.parametersetplayer'),
        ),
    ]
