# Generated by Django 4.2.5 on 2023-11-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_parametersetbarrier_parameter_set_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetground',
            name='parameter_set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_grounds_b', to='main.parametersetgroup'),
        ),
    ]
