# Generated by Django 4.2.7 on 2023-11-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_parametersetground_parameter_set_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgroup',
            name='parameter_set_hat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_groups_b', to='main.parametersethat'),
        ),
    ]
