# Generated by Django 4.2.5 on 2023-11-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_parametersetgroup_parameter_set_hat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersethat',
            options={'ordering': ['info'], 'verbose_name': 'Parameter Set Hat', 'verbose_name_plural': 'Parameter Set Hats'},
        ),
    ]
