# Generated by Django 4.2.5 on 2023-11-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_alter_parametersethat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersetnotice',
            options={'ordering': ['start_period', 'start_time'], 'verbose_name': 'Parameter Set Notice', 'verbose_name_plural': 'Parameter Set Notices'},
        ),
        migrations.AddField(
            model_name='parametersetnotice',
            name='help_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_notices', to='main.helpdocs'),
        ),
    ]
