# Generated by Django 4.2.9 on 2024-03-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_remove_parameterset_enable_hats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='id_string',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
