# Generated by Django 4.2.13 on 2024-06-10 21:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_session_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='replay_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Replay Data'),
        ),
    ]
