# Generated by Django 4.2.13 on 2024-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetbarrier',
            name='period_on_modulus_answer',
            field=models.IntegerField(default=0, verbose_name='Period On Modulus Answer'),
        ),
    ]
