# Generated by Django 4.2.13 on 2024-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_parametersetbarrier_period_on_modulus_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetbarrier',
            name='period_on_modulus',
            field=models.IntegerField(default=100, verbose_name='Period On Modulus'),
        ),
    ]
