# Generated by Django 4.2.13 on 2024-07-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_alter_parametersetbarrier_period_on_modulus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetGroupGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info')),
                ('start_x', models.IntegerField(default=50, verbose_name='Location X')),
                ('start_y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('text', models.CharField(default='Closed until period N', max_length=100, verbose_name='Text')),
                ('rotation', models.IntegerField(default=0, verbose_name='Rotation')),
                ('period_on', models.IntegerField(default=1, verbose_name='Period On')),
                ('period_off', models.IntegerField(default=14, verbose_name='Period Off')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_group_gates_a', to='main.parameterset')),
                ('parameter_set_allowed_groups', models.ManyToManyField(related_name='parameter_set_group_gates_b', to='main.parametersetgroup')),
                ('parameter_set_allowed_players', models.ManyToManyField(related_name='parameter_set_group_gates_c', to='main.parametersetplayer')),
            ],
            options={
                'verbose_name': 'Parameter Set Group Gate',
                'verbose_name_plural': 'Parameter Set Group Gates',
                'ordering': ['id'],
            },
        ),
    ]
