# Generated by Django 4.2.13 on 2024-07-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_parametersetgroupgate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetgroupgate',
            name='parameter_set_allowed_players',
        ),
    ]
