# Generated by Django 4.2.13 on 2024-07-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_remove_parametersetgroupgate_parameter_set_allowed_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetgroupgate',
            name='max_players_per_group',
            field=models.IntegerField(default=1, verbose_name='Max Players Per Group'),
        ),
        migrations.AddField(
            model_name='parametersetgroupgate',
            name='parameter_set_ground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_group_gates_c', to='main.parametersetground'),
        ),
    ]
