# Generated by Django 4.2.13 on 2024-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_parametersetgroupgate_max_players_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='patch_growth_example',
            field=models.TextField(blank=True, default='0 → 2,2 → 4,4 → 16', null=True, verbose_name='Patch Growth Example'),
        ),
    ]
