'''
build forms
'''

from .login_form import LoginForm
from .parameters_form import ParametersForm
from .session_form import SessionForm
from .session_send_invitation_form import  SessionInvitationForm
from .import_parameters_form import ImportParametersForm

from .parameter_set_form import ParameterSetForm
from .parameter_set_group_form import ParameterSetGroupForm
from .parameter_set_player_form import ParameterSetPlayerForm
from .parameter_set_wall_form import ParameterSetWallForm
from .parameter_set_ground_form import ParameterSetGroundForm
from .parameter_set_field_type_form import ParameterSetFieldTypeForm
from .parameter_set_field_form import ParameterSetFieldForm
from .parameter_set_notice_form import ParameterSetNoticeForm
from .parameter_set_barrier_form import ParameterSetBarrierForm
from .parameter_set_patch_form import ParameterSetPatchForm
from .parameter_set_hat_form import ParameterSetHatForm
from .parameter_set_group_gate_form import ParameterSetGroupGateForm

from .session_player_name_etc_form import StaffEditNameEtcForm

from .session_form_admin import SessionFormAdmin
from .instruction_set_form_admin import InstructionSetFormAdmin
from .instruction_form_admin import InstructionFormAdmin
from .help_doc_subject_form_admin import HelpDocSubjectFormAdmin

from .end_game_form import EndGameForm
from .interaction_form import InteractionForm
